# Generated by Django 3.1.7 on 2023-11-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingCross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date_of_reading', models.DateTimeField()),
                ('question_asked', models.TextField()),
                ('pos1_card', models.IntegerField()),
                ('pos2_card', models.IntegerField()),
                ('pos3_card', models.IntegerField()),
                ('pos4_card', models.IntegerField()),
                ('pos5_card', models.IntegerField()),
                ('pos6_card', models.IntegerField()),
                ('pos7_card', models.IntegerField()),
                ('pos8_card', models.IntegerField()),
                ('pos9_card', models.IntegerField()),
                ('pos10_card', models.IntegerField()),
                ('pos1_mytake', models.TextField()),
                ('pos2_mytake', models.TextField()),
                ('pos3_mytake', models.TextField()),
                ('pos4_mytake', models.TextField()),
                ('pos5_mytake', models.TextField()),
                ('pos6_mytake', models.TextField()),
                ('pos7_mytake', models.TextField()),
                ('pos8_mytake', models.TextField()),
                ('pos9_mytake', models.TextField()),
                ('pos10_mytake', models.TextField()),
                ('pos1_recap', models.TextField()),
                ('pos2_recap', models.TextField()),
                ('pos3_recap', models.TextField()),
                ('pos4_recap', models.TextField()),
                ('pos5_recap', models.TextField()),
                ('pos6_recap', models.TextField()),
                ('pos7_recap', models.TextField()),
                ('pos8_recap', models.TextField()),
                ('pos9_recap', models.TextField()),
                ('pos10_recap', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
