# Generated by Django 3.1.7 on 2023-11-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231102_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcross',
            name='date_of_reading',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos10_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos10_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos1_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos1_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos2_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos2_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos3_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos3_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos4_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos4_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos5_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos5_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos6_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos6_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos7_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos7_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos8_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos8_recap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos9_mytake',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingcross',
            name='pos9_recap',
            field=models.TextField(blank=True),
        ),
    ]
