# Generated by Django 3.1.7 on 2023-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231103_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossreading',
            name='pos10_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos1_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos2_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos3_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos4_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos5_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos6_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos7_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos8_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crossreading',
            name='pos9_card',
            field=models.CharField(max_length=100),
        ),
    ]
